### ISSUE TITLE
Add license checker

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/project-checks#10]
Probably we can use https://github.com/google/go-licenses

e.g., https://github.com/lima-vm/lima/pull/1832/files

**Comment by coderbirju** [comment]
Hey there,

I'd like to take this issue up. 

Following @AkihiroSuda 's advice I made some changes to the yaml file in[ my fork of project-checks](https://github.com/containerd/project-checks/compare/main...coderbirju:project-checks:main). However I'm running into issues testing this change.

Steps: 
1. Created a fork of containerd/project-checks and merged the necessary updates to the action.yml file
2. Generated binaries of the project-checks repository
3. Updated the binaries in the [ci.yml](https://github.com/coderbirju/containerd/pull/1/files) file in my forked repo of containerd

I wanted to know if I'm on the right track. Is there a better way to test these changes? Would appreciate any insights. 
Thanks!

**Comment by coderbirju** [comment]
Was able to figure this out. 

PR #11 

Testing: 
[Successful workflow run](https://github.com/coderbirju/containerd/pull/3/checks)

**Comment by coderbirju** [comment]
Could we maybe add a CI workflow that could test changes to project-checks with all of the dependent repos? 
Also an update to the tags in the repos is required, maybe we can automate that as well?

Tracking this in #12

**Comment by estesp** [comment]
Solved via #11
